catalogos:
  tipos_tienda:
    - nombre: 'hipermercado'
      probabilidad: 20
    - nombre: 'supermercado'
      probabilidad: 55
    - nombre: 'tienda_conveniencia'
      probabilidad: 25

  canales:
    - nombre: 'tienda'
      probabilidad: 82
    - nombre: 'ecommerce'
      probabilidad: 14
    - nombre: 'marketplace'
      probabilidad: 04